### ISSUE TITLE
Name expiry time

### ISSUE THREAD

**Issue by jbuck306** [bricefrisco/NamesLoL#5]
Do you know if names expire at exactly hh:mm:ss.00 for example? Or do you know if the milliseconds come into play aswell?

**Comment by bricefrisco** [comment]
We use the [Inactive Summoner Name Rules](https://support-leagueoflegends.riotgames.com/hc/en-us/articles/201751914-Inactive-Summoner-Name-Rules#:~:text=Each%20Summoner%20name%20will%20have,6%2C%20up%20to%2030%20months.) to estimate when a name will become available.

Riot does not disclose when a name will become available. See [Can you please tell me when name X becomes available?](https://support-leagueoflegends.riotgames.com/hc/en-us/articles/201751914-Inactive-Summoner-Name-Rules#q3).

Thus, we're not sure how Riot handles name expiration internally, only what they have made public.
